name: Generate Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Metrics embed
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          # Options
          user: xunholy
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Australia/Sydney
          plugin_sponsors: yes
          plugin_sponsors_sections: goal, about
          plugin_traffic: yes
